src/Kate.Web.Mvc/Areas/Admin/Controllers/ArticleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Kate.Article;
using Microsoft.Extensions.Options;
using Microsoft.AspNetCore.Hosting;
using Kate.Controllers;
using Kate.Utils;
using Kate.Services.GenericDtos;
using Kate.Article.Dto;
using Kate.UploadFile;
using Abp.AspNetCore.Mvc.Authorization;

namespace Kate.Web.Mvc.Areas.Admin.Controllers
{
    [Area("Admin")]
    [AbpMvcAuthorize]
    public class ArticleController : KateControllerBase
    {
        private readonly BaseArticleAppService _articleService;
        private readonly IOptions<FilePathSetting> _filePath;
        private readonly IHostingEnvironment _appEnvironment;

        [BindProperty]
        public FileUpload FileUpload { get; set; }

        public ArticleController(BaseArticleAppService articleService, IOptions<FilePathSetting> filePath, IHostingEnvironment appEnvironment)
        {
            _articleService = articleService;
            _filePath = filePath;
            _appEnvironment = appEnvironment;
        }

        public IActionResult Index()
        {
            var model = _articleService.GetTableViewModels();

            return View(model);
        }

        public IActionResult Manage(int id)
        {
            var model = _articleService.GetViewModel(id);

            return View(model);
        }

        [HttpPost]
        public async System.Threading.Tasks.Task<IActionResult> Save(ArticleManageDto model)
        {
            if (!ModelState.IsValid)
            {
                _articleService.FillManageDtoWithInitialData(model);
                return View("Manage", model);
            }

            if (FileUpload.UploadPdf != null && FileUpload.UploadPdf.Length != 0)
                model.PdfFilePath = await SaveFileOnDisk.ProcessFormFile(FileUpload.UploadPdf, ModelState, _appEnvironment.WebRootPath + _filePath.Value.PdfWordFolderPath);
            if (FileUpload.UploadWord != null && FileUpload.UploadWord.Length != 0)
                model.WordFilePath = await SaveFileOnDisk.ProcessFormFile(FileUpload.UploadWord, ModelState, _appEnvironment.WebRootPath + _filePath.Value.PdfWordFolderPath);
            if (FileUpload.UploadPicture != null && FileUpload.UploadPicture.Length != 0)
                model.MainPhotoPath = await SaveFileOnDisk.ProcessFormFile(FileUpload.UploadPicture, ModelState, _appEnvironment.WebRootPath + _filePath.Value.ImageFolderPath);

            if (!ModelState.IsValid)
            {
                _articleService.FillManageDtoWithInitialData(model);
                return View("Manage", model);
            }
            else
                _articleService.Save(model);

            return RedirectToAction("index");
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {
            _articleService.Delete(id);

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
                _articleService.Dispose();

            base.Dispose(disposing);
        }
    }
}

src/Kate.Web.Mvc/Areas/Admin/Views/Article/Index.cshtml
@using Kate.Web.Startup
@using Kate.Article.Dto
@using Kate.Web.Extensions
@model IEnumerable<ArticleTableDto>
@{
    ViewBag.CurrentPageName = PageNames.DynamicMenu; // The menu item will be active for this page.
}

<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <h2>
                    სტატიები
                </h2>
                <ul class="header-dropdown m-r--5">
                    <li class="dropdown">
                        <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            <i class="material-icons">more_vert</i>
                        </a>
                        <ul class="dropdown-menu pull-right">
                            <li><a id="RefreshButton" href="javascript:void(0);" class="waves-effect waves-block"><i class="material-icons">refresh</i>Refresh</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
            <div class="body table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th>სახელი</th>
                            <th>სორტირების ინდექსი</th>
                            <th>მოკლე აღწერა</th>
                            <th>აღწერა</th>
                            <th>ვიდეოს ლინკი</th>
                            <th>სიახლის თარიღი</th>
                            <th>ჩანს თუ არა სლაიდერში</th>
                            <th>მიმაგრებული სურათი</th>
                            <th>მიმაგრებული ფაილი word</th>
                            <th>მიმაგრებული ფაილი pdf</th>
                            <th>ჩანს თუ არა საიტზე</th>
                            <th>ჩანს თუ არა მარჯვენა ყუთში</th>
                            <th>კატეგორია</th>
                            <th>საძიებო თაგები</th>
                            <th>მოქმედებები</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var article in Model)
                        {
                        <tr>
                            <td>@article.Translation.Name</td>
                            <td>@article.SortIndex</td>
                            <td>@article.Translation.ShortDescription</td>
                            <td data-toggle="modal"
                                data-target="#DescritionModal"
                                data-text="@article.Translation.Description"
                                onclick="$('.modal-text').html($(this).data('text'))">
                                @article.Translation.Description.Slice(70)
                            </td>
                            <td>@article.VideoEmbed</td>
                            <td>@article.CreateDate</td>
                            <td><i class="material-icons" style="color:@(article.ShowInMainSlider ? "green":"red");">@(article.ShowInMainSlider ? "check_box" : "indeterminate_check_box")</i></td>
                            <td>
                                @if (string.IsNullOrEmpty(article.MainPhotoPath))
                                {
                                    <span>ფაილი არ არის მიმაგრებული</span>
                                }
                                else
                                {
                                    <a href="@(FolderPaths.Value.ImageFolderPath + article.MainPhotoPath)">სურათის სანახავად დააჭირე</a>
                                }
                            </td>
                            <td>
                                @if (string.IsNullOrEmpty(article.WordFilePath))
                                {
                                    <span>ფაილი არ არის მიმაგრებული</span>
                                }
                                else
                                {
                                    <a href="@(FolderPaths.Value.PdfWordFolderPath + article.WordFilePath)">@article.FileUserReadableName</a>
                                }
                            </td>
                            <td>
                                @if (string.IsNullOrEmpty(article.PdfFilePath))
                                {
                                    <span>ფაილი არ არის მიმაგრებული</span>
                                }
                                else
                                {
                                    <a href="@(FolderPaths.Value.PdfWordFolderPath + article.PdfFilePath)">@article.FileUserReadableName</a>
                                }
                            </td>
                            <td><i class="material-icons" style="color:@(article.ShowOnSite ? "green":"red");">@(article.ShowOnSite ? "check_box" : "indeterminate_check_box")</i></td>
                            <td><i class="material-icons" style="color:@(article.ShowOnMainPageBox ? "green":"red");">@(article.ShowOnMainPageBox ? "check_box" : "indeterminate_check_box")</i></td>
                            <td>@article.CategoryName</td>
                            <td>
                            <td class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                    <i class="material-icons">menu</i>
                                </a>
                                <ul class="dropdown-menu pull-right">
                                    @foreach (var tag in article.SearchTags)
                                    {
                                        <li><a href="#" class="waves-effect waves-block edit-user"><i class="material-icons">edit</i>@tag.Tag</a></li>
                                    }
                                </ul>
                            </td>

                            <td class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                    <i class="material-icons">menu</i>
                                </a>
                                <ul class="dropdown-menu pull-right">
                                    <li>
                                        <form asp-action="Delete" method="post">
                                            <input type="hidden" value="@article.Id" name="id" />
                                            <button type="submit" class="btn btn-primary">წაშლა</button>
                                        </form>
                                    </li>
                                    <li>
                                        <a class="waves-effect waves-block edit-user" asp-action="Manage" asp-controller="Article" asp-route-id="@article.Id"><i class="material-icons">edit</i>რედაქტირება</a>
                                    </li>
                                </ul>
                            </td>
                        </tr>
                        }
                    </tbody>
                </table>
                <a asp-action="Manage" asp-controller="Article">
                    <button type="button" class="btn btn-primary btn-circle waves-effect waves-circle waves-float pull-right">
                        <i class="material-icons">add</i>
                    </button>
                </a>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="DescritionModal" tabindex="-1" role="dialog" aria-labelledby="DescritionModal" data-backdrop="static">
    <div class="modal-dialog" role="dialog">

        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">აღწერა</h4>
            </div>
            <span class="modal-text"></span>
        </div>
    </div>
</div>

src/Kate.Web.Mvc/Areas/Admin/Views/Article/Manage.cshtml
@using Kate.Article.Dto
@using Kate.Web.Areas.Admin.Models
@using Kate.EntityFrameworkCore.Entities
@using Kate.Localization;
@model ArticleManageDto
@{
    ViewData["Title"] = "Manage";
    int i = -1;
}

<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <a asp-controller="article" asp-action="index" style="padding-left:90%">უკან დაბრუნება</a>
        <div class="card">
            <div class="header">
                <h2>
                    სტატიის რედაქტირება
                </h2>
            </div>
            <div class="body">
                <form asp-action="Save" method="post" enctype="multipart/form-data">
                    <input type="hidden" asp-for="Id" />

                    <div class="row clearfix">
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                            <div class="card">
                                <div class="header">
                                    <h2></h2>
                                </div>
                                <div class="body">
                                    <div class="row clearfix">
                                        <div class="col-md-6">
                                            <input type="checkbox" id="basic_checkbox_1" @(Model.ShowOnSite ? "Checked" : "") value="true" name="ShowOnSite" />
                                            <label for="basic_checkbox_1">გამოჩნდეს თუ არა საიტზე</label>
                                        </div>
                                        <div class="col-md-6">
                                            <input type="checkbox" id="basic_checkbox_2" @(Model.ShowOnMainPageBox ? "Checked" : "") value="true" name="ShowOnMainPageBox" />
                                            <label for="basic_checkbox_2">გამოჩნდეს მარჯვენა ყუთში</label>
                                        </div>
                                        <div class="col-md-6">
                                            <input type="checkbox" id="basic_checkbox_3" @(Model.ShowInMainSlider ? "Checked" : "") value="true" name="ShowInMainSlider" />
                                            <label for="basic_checkbox_3">გამოჩნდეს სლაიდერში</label>
                                        </div>
                                        <div class="col-md-2">
                                            <input type="number" class="form-control" value="@Model.SortIndex" name="SortIndex" />
                                            <label>სორტირების ინდექსი</label>
                                        </div>
                                        <div class="col-md-6">
                                            <p>
                                                <b>მიმაგრებული ფაილის დასახელება</b>
                                            </p>
                                            <div class="input-group">
                                                <div class="form-line">
                                                    <input type="text" class="form-control" placeholder="ტექსტი" value="@Model.FileUserReadableName" name="FileUserReadableName">
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <p>
                                                <b>ვიდეოს ემბედ ლინკი</b>
                                            </p>
                                            <div class="input-group">
                                                <div class="form-line">
                                                    <input type="text" class="form-control" placeholder="ტექსტი" value="@Model.VideoEmbed" name="VideoEmbed">
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        @Html.Partial("_Dropdown", new DropdownWiewModel { DropdownName = "კატეგორია", Dropdown = Model.Dropdown, BindName = "SelectedCategoryId" })
                    </div>
                    <div class="row clearfix">
                        @Html.Partial("_UploadPhoto", Model.MainPhotoPath)
                        @Html.Partial("_UploadFiles", new UploadFileViewModel { FileUserReadableName = Model.FileUserReadableName, PdfFilePath = Model.PdfFilePath, WordFilePath = Model.WordFilePath })
                    </div>

                    @Html.Partial("_Tags", Model.Tags)

                    @foreach (var translation in Model.Translations)
                    {
                        { i++; }

                        <input type="hidden" value="@translation.Id" name="Translations[@i].Id" />
                        <input type="hidden" value="@translation.LanguageId" name="Translations[@i].LanguageId" />

                        @switch (translation.LanguageId)
                        {
                            case (int)LanguageEnum.English:
                                <h2 class="card-inside-title">სათაური ინგლისურად</h2>
                                break;
                            case (int)LanguageEnum.Georgian:
                                <h2 class="card-inside-title">სათაური ქართულად</h2>
                                break;
                            case (int)LanguageEnum.French:
                                <h2 class="card-inside-title">სათაური ფრანგულად</h2>
                                break;
                            case (int)LanguageEnum.German:
                                <h2 class="card-inside-title">სათაური რუსულად</h2>
                                break;
                        }

                        <div class="row clearfix">
                            <div class="col-sm-12">
                                <div class="form-group form-group-lg">
                                    <div class="form-line">
                                        <input type="text" class="form-control" placeholder="გთხოვთ ჩაწეროთ დასახელება" name="Translations[@i].Name" value="@translation.Name" />
                                    </div>
                                </div>
                            </div>
                        </div>

                        @switch (translation.LanguageId)
                        {
                            case (int)LanguageEnum.English:
                                <h2 class="card-inside-title">მოკლე აღწერა ინგლისურად</h2>
                                break;
                            case (int)LanguageEnum.Georgian:
                                <h2 class="card-inside-title">მოკლე აღწერა ქართულად</h2>
                                break;
                            case (int)LanguageEnum.French:
                                <h2 class="card-inside-title">მოკლე აღწერა ფრანგულად</h2>
                                break;
                            case (int)LanguageEnum.German:
                                <h2 class="card-inside-title">მოკლე აღწერა რუსულად</h2>
                                break;
                        }

                        <textarea id="ckeditor-@(i+10)" name="Translations[@i].ShortDescription">@translation.ShortDescription</textarea>

                        @switch (translation.LanguageId)
                        {
                            case (int)LanguageEnum.English:
                                <h2 class="card-inside-title">აღწერა ინგლისურად</h2>
                                break;
                            case (int)LanguageEnum.Georgian:
                                <h2 class="card-inside-title">აღწერა ქართულად</h2>
                                break;
                            case (int)LanguageEnum.French:
                                <h2 class="card-inside-title">აღწერა ფრანგულად</h2>
                                break;
                            case (int)LanguageEnum.German:
                                <h2 class="card-inside-title">აღწერა რუსულად</h2>
                                break;
                        }

                        <textarea id="ckeditor-@i" name="Translations[@i].Description" required>@translation.Description</textarea>
                    }
                    <div class="saveButtonCenter">
                        <button type="submit" class="btn bg-orange waves-effect">
                            <i class="material-icons">save</i>
                            <span>შენახვა</span>
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>