src/Kate.Web.Mvc/Areas/Admin/Controllers/DecisionController.cs
using Abp.AspNetCore.Mvc.Authorization;
using Kate.Controllers;
using Kate.Decision;
using Kate.Decision.Dto;
using Kate.DynamicMenu;
using Kate.Services.GenericDtos;
using Kate.UploadFile;
using Kate.Utils;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;

namespace Kate.Web.Mvc.Areas.Admin.Controllers
{
    [Area("Admin")]
    [AbpMvcAuthorize]
    public class DecisionController : KateControllerBase
    {
        private readonly BaseDecisionAppService _decisionService;
        private readonly IOptions<FilePathSetting> _filePath;
        private readonly IHostingEnvironment _appEnvironment;

        [BindProperty]
        public FileUpload FileUpload { get; set; }

        public DecisionController(BaseDecisionAppService decisionService, IOptions<FilePathSetting> filePath, IHostingEnvironment appEnvironment)
        {
            _decisionService = decisionService;
            _filePath = filePath;
            _appEnvironment = appEnvironment;
        }

        public IActionResult Index()
        {
            var model = _decisionService.GetTableViewModels();

            return View(model);
        }

        public IActionResult Manage(int id)
        {
            var model = _decisionService.GetViewModel(id);

            return View(model);
        }

        [HttpPost]
        public async System.Threading.Tasks.Task<IActionResult> Save(DecisionManageDto model)
        {
            if (!ModelState.IsValid)
            {
                _decisionService.FillManageDtoWithInitialData(model);
                return View("Manage", model);
            }

            if (FileUpload.UploadPdf != null && FileUpload.UploadPdf.Length != 0)
                model.PdfFilePath = await SaveFileOnDisk.ProcessFormFile(FileUpload.UploadPdf, ModelState, _appEnvironment.WebRootPath + _filePath.Value.PdfWordFolderPath);
            if (FileUpload.UploadWord != null && FileUpload.UploadWord.Length != 0)
                model.WordFilePath = await SaveFileOnDisk.ProcessFormFile(FileUpload.UploadWord, ModelState, _appEnvironment.WebRootPath + _filePath.Value.PdfWordFolderPath);
            if (FileUpload.UploadPicture != null && FileUpload.UploadPicture.Length != 0)
                model.MainPhotoPath = await SaveFileOnDisk.ProcessFormFile(FileUpload.UploadPicture, ModelState, _appEnvironment.WebRootPath + _filePath.Value.ImageFolderPath);

            if (!ModelState.IsValid)
            {
                _decisionService.FillManageDtoWithInitialData(model);
                return View("Manage", model);
            }
            else
                _decisionService.Save(model);

            return RedirectToAction("index");
        }
        
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {
            _decisionService.Delete(id);

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
                _decisionService.Dispose();

            base.Dispose(disposing);
        }
    }
}

src/Kate.Web.Mvc/Areas/Admin/Views/Decision/Index.cshtml
@using Kate.Web.Startup
@using Kate.Decision.Dto
@using Kate.Web.Extensions
@model IEnumerable<DecisionTableDto>
@{
    ViewBag.CurrentPageName = PageNames.Decision; // The menu item will be active for this page.
}

<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <h2>
                    კანონმდებლობა
                </h2>
                <ul class="header-dropdown m-r--5">
                    <li class="dropdown">
                        <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            <i class="material-icons">more_vert</i>
                        </a>
                        <ul class="dropdown-menu pull-right">
                            <li><a id="RefreshButton" href="javascript:void(0);" class="waves-effect waves-block"><i class="material-icons">refresh</i>Refresh</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
            <div class="body table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th>სახელი</th>
                            <th>სორტირების ინდექსი</th>
                            <th>აღწერა</th>
                            <th>ფაილის ბმული</th>
                            <th>თარიღი</th>
                            <th>ჩანს თუ არა სლაიდერში</th>
                            <th>მიმაგრებული სურათი</th>
                            <th>მიმაგრებული ფაილი word</th>
                            <th>მიმაგრებული ფაილი pdf</th>
                            <th>ჩანს თუ არა საიტზე</th>
                            <th>ჩანს თუ არა მარჯვენა ყუთში</th>
                            <th>კატეგორია</th>
                            <th>საძიებო თაგები</th>
                            <th>მოქმედებები</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var decision in Model)
                        {
                            <tr>
                                <td>@decision.Translation.Name</td>
                                <td>@decision.SortIndex</td>
                                <td data-toggle="modal" data-target="#DescritionModal" data-text="@decision.Translation.Description" onclick="$('.modal-text').html($(this).data('text'))">
                                    @decision.Translation.Description.Slice(70)
                                </td>
                                <td>@decision.LinkToFile</td>
                                <td>@decision.DecisionDate</td>
                                <td><i class="material-icons" style="color:@(decision.ShowOnMainPage ? "green":"red");">@(decision.ShowOnMainPage ? "check_box" : "indeterminate_check_box")</i></td>
                                <td>
                                    @if (string.IsNullOrEmpty(decision.MainPhotoPath))
                                    {
                                        <span>ფაილი არ არის მიმაგრებული</span>
                                    }
                                    else
                                    {
                                        <a href="@(FolderPaths.Value.ImageFolderPath + decision.MainPhotoPath)">სურათის სანახავად დააჭირე</a>
                                    }
                                </td>
                                <td>
                                    @if (string.IsNullOrEmpty(decision.WordFilePath))
                                    {
                                        <span>ფაილი არ არის მიმაგრებული</span>
                                    }
                                    else
                                    {
                                        <a href="@(FolderPaths.Value.PdfWordFolderPath + decision.WordFilePath)">@decision.FileUserReadableName</a>
                                    }
                                </td>
                                <td>
                                    @if (string.IsNullOrEmpty(decision.PdfFilePath))
                                    {
                                        <span>ფაილი არ არის მიმაგრებული</span>
                                    }
                                    else
                                    {
                                        <a href="@(FolderPaths.Value.PdfWordFolderPath + decision.PdfFilePath)">@decision.FileUserReadableName</a>
                                    }
                                </td>
                                <td><i class="material-icons" style="color:@(decision.ShowOnSite ? "green":"red");">@(decision.ShowOnSite ? "check_box" : "indeterminate_check_box")</i></td>
                                <td><i class="material-icons" style="color:@(decision.ShowOnMainPageBox ? "green":"red");">@(decision.ShowOnMainPageBox ? "check_box" : "indeterminate_check_box")</i></td>
                                <td>@decision.CategoryName</td>
                                <td>
                                <td class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                        <i class="material-icons">menu</i>
                                    </a>
                                    <ul class="dropdown-menu pull-right">
                                        @foreach (var tag in decision.SearchTags)
                                        {
                                            <li><a href="#" class="waves-effect waves-block edit-user"><i class="material-icons">edit</i>@tag.Tag</a></li>
                                        }
                                    </ul>
                                </td>

                                <td class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                        <i class="material-icons">menu</i>
                                    </a>
                                    <ul class="dropdown-menu pull-right">
                                        <li>
                                            <form asp-action="Delete" method="post">
                                                <input type="hidden" value="@decision.Id" name="id" />
                                                <button type="submit" class="btn btn-primary">წაშლა</button>
                                            </form>
                                        </li>
                                        <li>
                                            <a class="waves-effect waves-block edit-user" asp-action="Manage" asp-controller="Decision" asp-route-id="@decision.Id"><i class="material-icons">edit</i>რედაქტირება</a>
                                        </li>
                                    </ul>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
                <a asp-action="Manage" asp-controller="Decision">
                    <button type="button" class="btn btn-primary btn-circle waves-effect waves-circle waves-float pull-right">
                        <i class="material-icons">add</i>
                    </button>
                </a>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="DescritionModal" tabindex="-1" role="dialog" aria-labelledby="DescritionModal" data-backdrop="static">
    <div class="modal-dialog" role="dialog">

        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">აღწერა</h4>
            </div>
            <span class="modal-text"></span>
        </div>
    </div>
</div>

src/Kate.Web.Mvc/Areas/Admin/Views/Decision/Manage.cshtml
@using Kate.Decision.Dto
@using Kate.Web.Areas.Admin.Models
@using Kate.EntityFrameworkCore.Entities
@model DecisionManageDto
@{
    ViewData["Title"] = "Manage";
    int i = -1;
}

<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <a asp-controller="Decision" asp-action="index" style="padding-left:90%">უკან დაბრუნება</a>
        <div class="card">
            <div class="header">
                <h2>
                    კანონმდებლობის რედაქტირება
                </h2>
            </div>
            <div class="body">
                <form asp-action="Save" method="post" enctype="multipart/form-data">
                    <input type="hidden" asp-for="Id" />

                    <div class="row clearfix">
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                            <div class="card">
                                <div class="header">
                                    <h2></h2>
                                </div>
                                <div class="body">
                                    <div class="row clearfix">
                                        <div class="col-md-6">
                                            <input type="checkbox" id="basic_checkbox_1" @(Model.ShowOnSite ? "Checked" : "") value="true" name="ShowOnSite" />
                                            <label for="basic_checkbox_1">გამოჩნდეს თუ არა საიტზე</label>
                                        </div>
                                        <div class="col-md-6">
                                            <input type="checkbox" id="basic_checkbox_2" @(Model.ShowOnMainPageBox ? "Checked" : "") value="true" name="ShowOnMainPageBox" />
                                            <label for="basic_checkbox_2">გამოჩნდეს მარჯვენა ყუთში</label>
                                        </div>
                                        <div class="col-md-6">
                                            <input type="checkbox" id="basic_checkbox_3" @(Model.ShowOnMainPage ? "Checked" : "") value="true" name="ShowInMainSlider" />
                                            <label for="basic_checkbox_3">გამოჩნდეს სლაიდერში</label>
                                        </div>
                                        <div class="col-md-2">
                                            <input type="number" class="form-control" value="@Model.SortIndex" name="SortIndex" />
                                            <label>სორტირების ინდექსი</label>
                                        </div>
                                        <div class="col-md-6">
                                            <p>
                                                <b>მიმაგრებული ფაილის დასახელება</b>
                                            </p>
                                            <div class="input-group">
                                                <div class="form-line">
                                                    <input type="text" class="form-control" placeholder="ტექსტი" value="@Model.FileUserReadableName" name="FileUserReadableName">
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <p>
                                                <b>ბმული</b>
                                            </p>
                                            <div class="input-group">
                                                <div class="form-line">
                                                    <input type="text" class="form-control" placeholder="ბმული" value="@Model.LinkToFile" name="LinkToFile">
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-sm-6">
                                            <p>
                                                <b>დოკუმენტის თარიღი</b>
                                            </p>
                                            <div class="form-group">
                                                <div class="form-line">
                                                    <input type="text" class="datepicker form-control" placeholder="Please choose a date..." value="@(Model.DocumentCameInAction != DateTime.MinValue ? Model.DocumentCameInAction.ToString() : "")" name="DocumentCameInAction">
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        @Html.Partial("_Dropdown", new DropdownWiewModel { DropdownName = "კატეგორია", Dropdown = Model.Dropdown, BindName = "SelectedCategoryId" })
                    </div>
                    <div class="row clearfix">
                        @Html.Partial("_UploadPhoto", Model.MainPhotoPath)
                        @Html.Partial("_UploadFiles", new UploadFileViewModel { FileUserReadableName = Model.FileUserReadableName, PdfFilePath = Model.PdfFilePath, WordFilePath = Model.WordFilePath })
                    </div>

                    @Html.Partial("_Tags", Model.Tags)

                    @foreach (var translation in Model.Translations)
                    {
                        { i++; }

                        @Html.Partial("_StandartTranslation", new TranslationViewModel { Indexer = i, Translation = translation })
                    }
                    <div class="saveButtonCenter">
                        <button type="submit" class="btn bg-orange waves-effect">
                            <i class="material-icons">save</i>
                            <span>შენახვა</span>
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>