src/Kate.Web.Mvc/Areas/Admin/Controllers/InnerComplaintController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Kate.InnerComplaint;
using Kate.Controllers;
using Abp.AspNetCore.Mvc.Authorization;
using Kate.InnerComplaint.Dto;

namespace Kate.Web.Mvc.Areas.Admin.Controllers
{
    [Area("Admin")]
    [AbpMvcAuthorize]
    public class InnerComplaintController : KateControllerBase
    {
        private readonly BaseInnerComplaintAppService _innerComplaintService;

        public InnerComplaintController(BaseInnerComplaintAppService innerComplaintService)
        {
           _innerComplaintService = innerComplaintService;
        }

        public ActionResult Index()
        {
            var model = _innerComplaintService.GetAboutUsReadViewModel();

            return View(model);
        }

        public IActionResult Manage()
        {
            var model = _innerComplaintService.GetAboutUsManageViewModel();

            return View(model);
        }

        [HttpPost]
        public IActionResult Save(InnerComplaintDto model)
        {
            if (ModelState.IsValid)
                _innerComplaintService.Update(model);
            else
                return View(model);

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _innerComplaintService.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

src/Kate.Web.Mvc/Areas/Admin/Views/InnerComplaint/Index.cshtml
@using Kate.Web.Startup
@using Kate.InnerComplaint.Dto;
@model InnerComplaintReadDto
@{
    ViewBag.CurrentPageName = PageNames.About; // The menu item will be active for this page.
}

<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <a asp-controller="innercomplaint" asp-action="manage" style="padding-left:90%">რედაქტირება</a>
        <div class="card">
            <div class="header">
                <h2>
                    @Model.Translation.Name
                </h2>
            </div>
            <div class="body">
                @Html.Raw(Model.Translation.Description)
            </div>
        </div>
    </div>
</div>

src/Kate.Web.Mvc/Areas/Admin/Views/InnerComplaint/Manage.cshtml
@using Kate.InnerComplaint.Dto;
@using Kate.Web.Areas.Admin.Models
@model InnerComplaintDto
@{
    ViewData["Title"] = "Manage";
    int i = -1;
}

<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <a asp-controller="InnerComplaint" asp-action="index" style="padding-left:90%">უკან დაბრუნება</a>
        <div class="card">
            <div class="header">
                <h2>

                </h2>
            </div>
            <div class="body">
                <form asp-action="Save" method="post" enctype="multipart/form-data">
                    <input type="hidden" asp-for="Id" />

                    @foreach (var translation in Model.Translations)
                    {
                        { i++; }

                        @Html.Partial("_StandartTranslation", new TranslationViewModel { Indexer = i, Translation = translation });
                    }

                    <button type="submit" class="btn bg-orange waves-effect">
                        <i class="material-icons">save</i>
                        <span>შენახვა</span>
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>